print('Enter your name:')
x = input()
print('Hello, ' + x)
a=input('Enter a value :')
b=input('Enter b value :')
sum=float(a)+float(b)
print('sum of two values',sum)
print( 'The sum of Given values {0} and {1} = {2}' . format( a, b, sum) )
sub=float(a)-float(b)
print('Difference between two value {0} and {1} = {2}' . format(a,b, sub))
div=float(a)/float(b)
print('Division of two value {0} and {1} = {2}' . format(a,b, div))
mul=float(a)*float(b)
print('Product of two value {0} and {1} = {2}' . format(a,b, mul))
avg=(float(a)*float(b))/2
print('Average of two value {0} and {1} = {2}' . format(a,b, avg))